import { StyleSheet } from 'react-native';
import { PRIMARY_COLOR, QUATERNARY_COLOR, SECONDARY_COLOR, TERTIARY_COLOR } from '../commons/constants';

export const stylesGlobal = StyleSheet.create({
    title:{
        color:SECONDARY_COLOR,
        fontSize:25,
        paddingHorizontal:30,
        paddingTop:70,
        fontWeight:'bold'
    },
    containerBody:{
        backgroundColor:SECONDARY_COLOR,
        borderTopLeftRadius:30,
        borderTopRightRadius:30,
        paddingHorizontal:30,
        paddingTop:40,
        paddingVertical:40,
    },
    titleWelcomw:{
        fontSize:17,
        fontWeight:'bold'
    },
    usuarioInput:{
        backgroundColor:QUATERNARY_COLOR,
        borderRadius:10,
        //marginTop:15,
        paddingHorizontal:20,
        marginVertical:7,
    },
    containerInput:{
        marginVertical:15,
    },
    button:{
        backgroundColor:TERTIARY_COLOR,
        paddingVertical:15,
        borderRadius:10,
    },
    buttonText:{
        textAlign:'center',
        color: SECONDARY_COLOR,
        fontSize:15,
        fontWeight:'bold'
    },
    iconPassword:{
        position:'absolute',
        bottom:15,
        right:10,
    },
    textRedirect:{
        marginTop:15,
        fontSize:15,
        color:PRIMARY_COLOR,
        fontWeight:'bold',
        textAlign:'center'
    },
    containerCard:{
        //flexDirection:'row',
        flex:1,
        justifyContent:'center',
        //alignItems:'center',
        padding:15,
        borderWidth:1,
        borderColor:QUATERNARY_COLOR,
        borderRadius:10,
        margin:7,
        borderStyle:'solid',
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 2.65,
        elevation: 4,
        
    },
    titleCard:{
        fontSize:16,
        fontWeight:'bold',
        //paddingLeft:10
    },
    imageCard:{
        width:90,
        height:80,
        borderRadius:10,
        marginBottom:10,
        alignSelf:'center',
        marginTop:10
    },
    iconCard:{
        flex:1,
        alignItems:'flex-end',
        
    },
    containerModal:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'rgba(0,0,0,0.5)'
    },
    bodyModal:{
        //margin:25,
        backgroundColor:SECONDARY_COLOR,
        borderRadius:10,
        padding:20,
    },
    headerModal:{
        flexDirection:'row',
        justifyContent:'space-between',
        borderBottomColor:QUATERNARY_COLOR,
        borderBottomWidth:1,
        padding:10
    },
    titleModal:{
        fontSize:18,
        fontWeight:'bold',
        width:'90%'
    },
    imageModal:{
        width:200,
        height:200,
        borderRadius:10,
        marginTop:10,
        alignSelf:'center'
    },
    containerbutonModal:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    butonModal:{
        backgroundColor:TERTIARY_COLOR,
        height:50,
        width:50,
        borderRadius:50,
        justifyContent:'center',
        alignItems:'center',
        margin:15
    },
    butoTextModal:{
        color:SECONDARY_COLOR,
        fontSize:25,
        //fontWeight:'bold'
    },
    priceModal:{
        fontSize:18,
        fontWeight:'bold',
        paddingBottom:10
    },
    textStock:{
        color:'red',
        fontSize:30,
        textAlign:'center',
        marginVertical:10,
        fontWeight:'bold'
    },
    headerHome:{
        flexDirection:'row',
        alignItems:'center',
    },
    iconHome:{
        flex:1,
        alignItems:'flex-end',
        paddingTop:5,
        paddingHorizontal:40
    },
    textIconCart:{
        backgroundColor:SECONDARY_COLOR,
        fontSize:13,
        fontWeight:'bold',
        paddingHorizontal:5,
        borderRadius:10,
    },
    headerTable:{
        flexDirection:'row',
        justifyContent:'space-between',
        //paddingHorizontal:10,
    },
    headerDescriptionTable:{
        flexDirection:'row',
    },
    headerTextTable:{
        fontSize:16,
        fontWeight:'bold',
        color:PRIMARY_COLOR
    },
    textWidhTable:{
        width:150,
        //textAlign:'center'
    },
    containerTotalPay:{
        alignItems:'flex-end',
        marginTop:10
    },
    textTotalPay:{
        fontSize:18,
        fontWeight:'bold',
    }
}) 